### ISSUE TITLE
List is empty

### ISSUE THREAD

**Issue by happysurf** [alexpdraper/reading-list#4]
This morning I discover your useful extension, all works fine but then when I click on the icon the saved list is empty.
Firefox ESR 52.2.1 on XP.

**Comment by whitecat** [comment]
I had the same problem. I think the app was released allowing the wrong version of Firefox. 

You can get the app working on Firefox 52-54 by changing a configuration flag for webextensions.
To do that:  "Please set webextensions.storage.sync.enabled to true in about:config"

The app only supports Firefox 54+, because default Firefox 54+ sets webextensions.storage.sync.enabled to true.
